name: example-workflow
on: [push]
jobs:
  production-deploy:
    if: github.repository == 'actions-joindevop/github-actions-practice'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '14'
      - run: npm install -g bats
