name: Sequential
on:
  push:
    branches: [ main ]
jobs:
    my_first_job:
      runs-on: ubuntu-latest
      name: My first job
    my_second_job:
      runs-on: ubuntu-latest
      name: My second job
