name: Sequential
on:
  push:
    branches: [ main ]
jobs:
    my_first_job:
      runs-on: ubuntu-latest
      steps:
        - name: My first job
          run: echo "First job"
    my_second_job:
      runs-on: ubuntu-latest
      steps:
        - name: My second job
          run: echo "Second job"
